### ISSUE TITLE
Typed property Typhoon\Reflection\ClassReflection::$changeDetector must not be accessed before initialization

### ISSUE THREAD

**Issue by root-aza** [typhoon-php/reflection#18] opened 2023-09-29 07:18 UTC
```php
$property = $this->reflector->reflectClass($reflection->class)
          ->getProperty($reflection->name);

dump($property, $property->getType());
```

```stacktrace
Error:
Typed property Typhoon\Reflection\ClassReflection::$changeDetector must not be accessed before initialization

  at vendor/typhoon/reflection/src/ClassReflection.php:116
  at Typhoon\Reflection\ClassReflection->getChangeDetector()
     (vendor/typhoon/reflection/src/Reflector/Cache/ChangeDetectingReflectionCache.php:25)
  at Typhoon\Reflection\Reflector\Cache\ChangeDetectingReflectionCache->getReflection('Typhoon\\Reflection\\ClassReflection', 'App\\FinanceBus\\Mts\\View\\Specification')
     (vendor/typhoon/reflection/src/Reflector/Context.php:165)
  at Typhoon\Reflection\Reflector\Context->resolveReflection('Typhoon\\Reflection\\ClassReflection', 'App\\FinanceBus\\Mts\\View\\Specification', object(Closure))
     (vendor/typhoon/reflection/src/Reflector/Context.php:127)
  at Typhoon\Reflection\Reflector\Context->reflectClass('App\\FinanceBus\\Mts\\View\\Specification')
     (vendor/typhoon/reflection/src/TyphoonReflector.php:99)
  at Typhoon\Reflection\TyphoonReflector->reflectClass('App\\FinanceBus\\Mts\\View\\Specification')
     (src/Infrastructure/ApiDoc/Describer/Property/NumericStringRelationDescriber.php:28)
  at App\Infrastructure\ApiDoc\Describer\Property\NumericStringRelationDescriber->describe(object(ReflectionProperty), object(Property), null)
     (vendor/poscredit/mdm-struct/src/Bridge/NelmioApiDoc/Describer/Model/PropertyObjectDescriber.php:80)
  at PosCredit\MDM\Struct\Bridge\NelmioApiDoc\Describer\Model\PropertyObjectDescriber->describe(object(Model), object(Schema))
     (vendor/nelmio/api-doc-bundle/Model/ModelRegistry.php:96)
  at Nelmio\ApiDocBundle\Model\ModelRegistry->registerSchemas()
     (vendor/nelmio/api-doc-bundle/ApiDocGenerator.php:117)
  at Nelmio\ApiDocBundle\ApiDocGenerator->generate()
     (vendor/nelmio/api-doc-bundle/Render/RenderOpenApi.php:76)
  at Nelmio\ApiDocBundle\Render\RenderOpenApi->render('html', 'default', array('assets_mode' => 'bundle'))
     (vendor/nelmio/api-doc-bundle/Render/RenderOpenApi.php:61)
  at Nelmio\ApiDocBundle\Render\RenderOpenApi->renderFromRequest(object(Request), 'html', 'default', array('assets_mode' => 'bundle'))
     (vendor/nelmio/api-doc-bundle/Controller/SwaggerUiController.php:37)
  at Nelmio\ApiDocBundle\Controller\SwaggerUiController->__invoke(object(Request), 'default')
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:184)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/Users/aza/PhpstormProjects/rest_api_pos/vendor/autoload_runtime.php')
     (public/index.php:7
```

**Comment by root-aza** [comment] 2023-09-29 07:25
di configuration

```php
<?php

declare(strict_types=1);

use Symfony\Component\Cache\Psr16Cache;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

use function Symfony\Component\DependencyInjection\Loader\Configurator\inline_service;
use function Symfony\Component\DependencyInjection\Loader\Configurator\service;

use Typhoon\Reflection\TyphoonReflector;

return static function (ContainerConfigurator $di): void {
    $di->services()
            ->defaults()
            ->autowire()
            ->autoconfigure()

        ->set(TyphoonReflector::class)
            ->factory([TyphoonReflector::class, 'build'])
            ->args([
                '$cache' => inline_service(Psr16Cache::class)
                    ->args([
                        '$pool' => service('cache.app'),
                    ]),
            ])
    ;
};
```

**Comment by vudaltsov** [comment] 2023-09-29 08:14
Hi! Thank you for the issue! I used exactly same configs with Symfony 6.3.4 and failed to reproduce the issue. What Symfony version do you have? In particular, `symfony/cache` version.

**Comment by root-aza** [comment] 2023-09-29 09:04
> Hi! Thank you for the issue! I used exactly same configs with Symfony 6.3.4 and failed to reproduce the issue. What Symfony version do you have? In particular, `symfony/cache` version.

symfony/cache v6.2.12
symfony/framework-bundle v6.2.12

**Comment by vudaltsov** [comment] 2023-09-29 14:10
I have installed cache v6.2.12 and still cannot reproduce the issue.

1. Try to clear cache and run your command again.
2. Do you have default `framework.cache` config in Symfony? Please, send the `bin/console debug:config framework cache` output.
3. The best way to find the bug would be to make a small reproducer project to show your problem. Or I could call you via google meet and we could debug that online.

**Comment by vudaltsov** [comment] 2023-09-30 09:39
This should be indeed fixed on Symfony side: `FilesystemAdapter` currently does not support classes with `__serialize` and no `__unserialize`. But I fixed that on our side for now via https://github.com/typhoon-php/reflection/commit/51650a0d369a6cb26e375a100a5c48c8a2a03243.

**Closed as completed by vudaltsov** 2023-09-30 09:39 UTC

**Comment by vudaltsov** [comment] 2023-09-30 10:44
For the record. The problem was with `igbinary` serialization only. @root-aza had this extension enabled, while I didn't. Symfony cache prefers to use `igbinary` if it exists.

The problem with igbinary is that it does not dynamically detect property visibility when deserializing. So if you have `__serialize` only and it returns property name without null-bytes (like public ones), igbinary deserializes them as public even if they are actually private or protected. Since the property is not public, cache creates dynamically while the actual property is not initialized. Now fixed.
